#!/usr/local/bin/bash

#GIT AUTOCOMPLETE (VIA BREW "bash_completion")
if [ -f `brew --prefix`/etc/bash_completion.d/git-completion.bash ]; then
  . `brew --prefix`/etc/bash_completion.d/git-completion.bash
fi
