#!/usr/local/bin/bash

#NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#NPM
alias npmr='npm run'
alias npmf='nvm install && npm install'
alias npmff='rm -rf node_modules && npmf'
alias npmfr='npmf && npmr'
alias npmffr='npmff && npmr'

#NODEJS
export PATH=./node_modules/.bin:$PATH
